package domain

import (
	"time"
)

// TradeRecord represents a trade execution record from MT4 / database.
type TradeRecord struct {
	ID         int64    `json:"id" db:"id"`
	Ticket     int64    `json:"ticket" db:"ticket"`
	Symbol     string   `json:"symbol" db:"symbol"`
	Action     string   `json:"action" db:"action"` // BUY / SELL
	Lots       float64  `json:"lots" db:"lots"`
	OpenPrice  float64  `json:"open_price" db:"open_price"`
	ClosePrice *float64 `json:"close_price,omitempty" db:"close_price"`
	OpenTime   string   `json:"open_time" db:"open_time"`
	CloseTime  *string  `json:"close_time,omitempty" db:"close_time"`
	Profit     float64  `json:"profit" db:"profit"`
	Comment    string   `json:"comment" db:"comment"`
	CreatedAt  string   `json:"created_at" db:"created_at"`
}

// Tick represents incoming market tick data.
type Tick struct {
	ID        int64   `json:"id" db:"id"`
	Symbol    string  `json:"symbol" db:"symbol"`
	Bid       float64 `json:"bid" db:"bid"`
	Ask       float64 `json:"ask" db:"ask"`
	Time      string  `json:"time" db:"time"`
	Volume    float64 `json:"volume" db:"volume"`
	CreatedAt string  `json:"created_at" db:"created_at"`
}

// Signal represents a trading signal generated by strategy.
type Signal struct {
	ID             int64   `json:"id" db:"id"`
	Symbol         string  `json:"symbol" db:"symbol"`
	Action         string  `json:"action" db:"action"` // BUY / SELL / CLOSE_ALL / HOLD
	Lot            float64 `json:"lot" db:"lot"`
	StopLossPips   float64 `json:"stop_loss_pips" db:"stop_loss_pips"`
	TakeProfitPips float64 `json:"take_profit_pips" db:"take_profit_pips"`
	Reason         string  `json:"reason" db:"reason"`
	CreatedAt      string  `json:"created_at" db:"created_at"`
}

// TradeMetrics holds aggregate performance statistics.
type TradeMetrics struct {
	TotalTrades       int           `json:"total_trades"`
	WinningTrades     int           `json:"winning_trades"`
	LosingTrades      int           `json:"losing_trades"`
	WinRate           float64       `json:"win_rate"`         // e.g. 66.7
	TotalProfit       float64       `json:"total_profit"`     // e.g. 38000.0
	GrossProfit       float64       `json:"gross_profit"`     // e.g. 40000.0
	GrossLoss         float64       `json:"gross_loss"`       // e.g. 2000.0
	ProfitFactor      float64       `json:"profit_factor"`    // e.g. 20.0
	MaxDrawdown       float64       `json:"max_drawdown"`     // e.g. 2000.0
	MaxDrawdownPct    float64       `json:"max_drawdown_pct"` // e.g. 1.4%
	AvgTradeProfit    float64       `json:"avg_trade_profit"` // e.g. 12666.7
	LargestWin        float64       `json:"largest_win"`      // e.g. 25000.0
	LargestLoss       float64       `json:"largest_loss"`     // e.g. -2000.0
	RecommendedLot    float64       `json:"recommended_lot"`  // e.g. 0.25 (0.10 ~ 0.50 Lot)
	ConsecutiveWins   int           `json:"consecutive_wins"`
	ConsecutiveLosses int           `json:"consecutive_losses"`
	Trades            []TradeRecord `json:"trades"`
}

// AiEvaluationReport represents a Gemini generated review of trading performance.
type AiEvaluationReport struct {
	ID           int64     `json:"id"`
	Title        string    `json:"title"`
	OverallRank  string    `json:"overall_rank"` // S, A, B, C
	Summary      string    `json:"summary"`
	Strengths    []string  `json:"strengths"`
	Weaknesses   []string  `json:"weaknesses"`
	ActionPoints []string  `json:"action_points"`
	RawReport    string    `json:"raw_report"`
	CreatedAt    time.Time `json:"created_at"`
}

// IpcRequest defines incoming IPC messages from Rust Gateway.
type IpcRequest struct {
	Type      string  `json:"type"` // CHECK_SIGNAL, PUSH_TICK, PING
	ImagePath string  `json:"image_path,omitempty"`
	Symbol    string  `json:"symbol,omitempty"`
	Action    string  `json:"action,omitempty"`
	Price     float64 `json:"price,omitempty"`
	Lot       float64 `json:"lot,omitempty"`
}

// IpcResponse defines outgoing IPC responses to Rust Gateway.
type IpcResponse struct {
	Type           string  `json:"type"` // SIGNAL_DECISION, ACK, PONG, ERROR
	Status         string  `json:"status,omitempty"`
	Symbol         string  `json:"symbol,omitempty"`
	Action         string  `json:"action,omitempty"`
	Decision       string  `json:"decision,omitempty"` // EXECUTE / REJECT / WAIT
	Confidence     float64 `json:"confidence,omitempty"`
	MatchedPattern string  `json:"matched_pattern,omitempty"`
	Reason         string  `json:"reason,omitempty"`
	Message        string  `json:"message,omitempty"`
}

// KillSwitchStatus represents the current state of emergency kill switch.
type KillSwitchStatus struct {
	Active      bool       `json:"active"`
	TriggeredAt *time.Time `json:"triggered_at,omitempty"`
	Reason      string     `json:"reason,omitempty"`
}
